name: CI
on:
  pull_request:
    branches: [main]
jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # needed so that we can check the repo age
          fetch-depth: 0
      - run: npx awesome-lint
